### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by vesperyn** [clear-leo/BrainFuck-rs#1]
Hi, just wanted to ask if this interpreter is supported on Linux, more specifically Ubuntu, as that is what i primarily run for programming. Installation to the PATH didn't work (obviously cuz I'm running Unix), so I wanted to ask if there is a way I could run it locally, not globally (without PATH). I tried to run the code below but it didn't work.
PS: I know nothing about rust.
```
astridot@ORBIT:~/Desktop/Project/TestingPlayground$ rustc BrainFuck-rs/src/main.rs
error[E0433]: failed to resolve: use of undeclared crate or module `brainfuck`
  --> BrainFuck-rs/src/main.rs:19:36
   |
19 | MIT OR Apache-2.0 clearleo 2024"#, brainfuck::VERSION, brainfuck::UPDATE_DATE);
   |                                    ^^^^^^^^^ use of undeclared crate or module `brainfuck`

error[E0433]: failed to resolve: use of undeclared crate or module `brainfuck`
  --> BrainFuck-rs/src/main.rs:19:56
   |
19 | MIT OR Apache-2.0 clearleo 2024"#, brainfuck::VERSION, brainfuck::UPDATE_DATE);
   |                                                        ^^^^^^^^^ use of undeclared crate or module `brainfuck`

error[E0433]: failed to resolve: use of undeclared crate or module `brainfuck`
  --> BrainFuck-rs/src/main.rs:23:9
   |
23 |         brainfuck::interpret_ui();
   |         ^^^^^^^^^ use of undeclared crate or module `brainfuck`

error[E0433]: failed to resolve: use of undeclared crate or module `brainfuck`
  --> BrainFuck-rs/src/main.rs:41:5
   |
41 |     brainfuck::run_str(&file_contents);
   |     ^^^^^^^^^ use of undeclared crate or module `brainfuck`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0433`.
```

**Comment by clear-leo** [comment]
Hey no worries, this interpreter was specifically made in linux and tested in linux. The problem you're having is using rustc, you have to use cargo. If you've already installed rustc it's more than probable that cargo is installed too. To confirm you do have cargo run ```cargo --version```. After you've confirmed cargo is installed just cd into the repository and either use ```cargo install --path .``` which will install it to path or ```cargo build --release``` to build the executable to the folder /target/release in the repo.

**Comment by clear-leo** [comment]
Sorry, closed the issue on accident.

**Comment by alklimakes** [comment]
[Screencast from 2024-12-18 14-32-22.webm](https://github.com/user-attachments/assets/673b8958-84b2-4292-bff2-ad6fb13560aa)

**Comment by alklimakes** [comment]
This is dae btw

**Comment by clear-leo** [comment]
Oh hi dae. Are you sure cargo is in your path? If it isn't, try adding ```export PATH=$PATH:~/.cargo/bin/``` to your ~/.bashrc or, for temp purposes since it'll only work for the current shell, run ```export PATH=$PATH:~/.cargo/bin/```

**Comment by alklimakes** [comment]
Ah, fixed. Thanks for the help!!

Edit: I thought I added the line to bashrc but I may have forgot to save the file lol
